name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: set up
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        run: go test ./... -v